const blocks3_input = [
  {
    pk: '#RE#5a49da85-21f6-4181-abe5-9cec43cb77a2',
    sk: '#PROP',
    add: '10641 Cory Lake Dr',
    additional_perks: 'Test3',
    address_city: 'Tampa',
    address_state: 'FL',
    fullAddress: '10641 Cory Lake Dr',
    address_zipCode: 33647,
    asset_price: 500000,
    city: 'Tampa',
    closing_cost: 10000,
    closing_date: '01-01-2023 11:28:55',
    company_name: '10641 Cory Lake Dr TPA LLC',
    expected_gross_rent_per_property: 120000,
    expected_gross_roi: 22.62443,
    expected_net_rent_per_property: 72700,
    expected_net_roi: 13.70664,
    expected_reserve_funds: 5000,
    expenses: 47300,
    gsi1_pk: '#USER#cc8c7284-ecbe-4ff4-af3b-d0facce0f3cf',
    gsi1_sk: '#RE#5a49da85-21f6-4181-abe5-9cec43cb77a2',
    gsi2_pk: '#10641 CORY LAKE DR#TAMPA#FL#33647',
    insurance: 2500,
    listing_price: 530400,
    maintenance_expense: 3600,
    maintenance_expense_in_percentage: 3,
    meta_land_revenue_stream: 'meta land revenue stream',
    meta_link:
      'https://www.zillow.com/homedetails/10641-Cory-Lake-Dr-Tampa-FL-33647/68581481_zpid/',
    net_rent_per_token: 6.73,
    offering_memorandum_date: '10-31-2022 11:28:55',
    parcel_area_acres: 0.31,
    parcel_area_sq_ft: 3382,
    parcel_building_count: 1,
    parcel_county_land_use_code: 'R001',
    parcel_county_land_use_description: 'Single Family',
    parcel_county_name: 'Tampa',
    parcel_depth_ft: '\'-1',
    parcel_frontage_ft: 50,
    parcel_municipality: 'Hillsborough',
    parcel_subdivision: 'Hillsborough',
    parcel_zoning: 'R001',
    platform_fees: 2400,
    platform_list_fees_in_percentage: 2,
    platform_listing_fees: 10400,
    property_description: 'Test3',
    property_mgmt_fees: 19,
    property_mgt_fees: 22800,
    property_taxes: 10000,
    re_id: '5a49da85-21f6-4181-abe5-9cec43cb77a2',
    renovation_costs: 5000,
    rent_processing_fees: 2,
    state: 'FL',
    structure_air_conditioning_type: 'Central air',
    structure_architecture_type: 'Modern',
    structure_basement_type: 'Finished Basement',
    structure_baths: 3,
    structure_beds_count: 4,
    structure_condition: 'New',
    structure_construction_type: 'Concrete',
    structure_effective_year_built: '\'-1',
    structure_exterior_wall_type: 'Concrete',
    structure_fireplaces: 0,
    structure_flooring_types: [
      {
        S: 'Marble',
      },
    ],
    structure_foundation_type: 'Concrete Slab',
    structure_heating_type: 'Central',
    structure_parking_spaces_count: 3,
    structure_parking_type: 'Parking 1',
    structure_partial_baths_count: 3,
    structure_roof_material_type: 'Concrete',
    structure_roof_style_type: 'Concrete',
    structure_stories: 2,
    structure_total_area_sq_ft: '\'-1',
    structure_units_count: 1,
    structure_year_built: 2005,
    taxes: [
      {
        M: {
          year: {
            N: '2021',
          },
          amount: {
            N: '5300',
          },
        },
      },
    ],
    token_id: 601,
    token_price: 49.11111,
    token_smart_contract_url:
      'https://mumbai.polygonscan.com/address/0x6aa43165f4664a5e7c69678a9865e280162cf31f',
    tokens_on_hold: 2,
    tokens_remaining: 10591,
    tokens_remaining_blockchain: 10613,
    tokens_sold: 211,
    total_investments: 520000,
    total_number_of_tokens: 10800,
    updated_at: '03-13-2023 12:51:04',
    userId: 'cc8c7284-ecbe-4ff4-af3b-d0facce0f3cf',
    utilities: 6000,
    valuation_forecast_standard_deviation: '\'-1',
    valuation_high: '\'-1',
    valuation_low: '\'-1',
    valuation_value: '\'-1',
    youtube_link:
      'https://www.zillow.com/homedetails/10641-Cory-Lake-Dr-Tampa-FL-33647/68581481_zpid/',
    zip: 33647,
  },
  {
    pk: '#RE#34dbbd69-af0c-421e-93f9-c6cb2b759c31',
    sk: '#PROP',
    add: '8452 Dunham Station Dr',
    additional_perks: 'Test2',
    address_city: 'Tampa',
    address_state: 'FL',
    fullAddress: '8452 Dunham Station Dr',
    address_zipCode: 33647,
    asset_price: 1082000,
    city: 'Tampa',
    closing_cost: 15000,
    closing_date: '01-02-2023 12:21:25',
    company_name: '8452 Dunham Station Dr TPA LLC',
    expected_gross_rent_per_property: 220000,
    expected_gross_roi: 19.46627,
    expected_net_rent_per_property: 145200,
    expected_net_roi: 12.84774,
    expected_reserve_funds: 6000,
    expenses: 74800,
    gsi1_pk: '#USER#cc8c7284-ecbe-4ff4-af3b-d0facce0f3cf',
    gsi1_sk: '#RE#34dbbd69-af0c-421e-93f9-c6cb2b759c31',
    gsi2_pk: '#8452 DUNHAM STATION DR#TAMPA#FL#33647',
    insurance: 4000,
    listing_price: 1130160,
    maintenance_expense: 6600,
    maintenance_expense_in_percentage: 3,
    meta_land_revenue_stream: 'meta land revenue stream',
    meta_link:
      'https://mumbai.polygonscan.com/address/0x6aa43165f4664a5e7c69678a9865e280162cf31f',
    net_rent_per_token: 6.37,
    offering_memorandum_date: '10-31-2022 12:21:25',
    parcel_area_acres: 2,
    parcel_area_sq_ft: 3935,
    parcel_building_count: 1,
    parcel_county_land_use_code: 'R001',
    parcel_county_land_use_description: 'Single Family',
    parcel_county_name: 'hillsborough',
    parcel_depth_ft: '\'-1',
    parcel_frontage_ft: 5,
    parcel_municipality: 'hillsborough',
    parcel_subdivision: 'hillsborough',
    parcel_zoning: 'R001',
    platform_fees: 4400,
    platform_list_fees_in_percentage: 2,
    platform_listing_fees: 22160,
    property_description: 'Test2',
    property_mgmt_fees: 19,
    property_mgt_fees: 41800,
    property_taxes: 12000,
    re_id: '34dbbd69-af0c-421e-93f9-c6cb2b759c31',
    renovation_costs: 5000,
    rent_processing_fees: 2,
    state: 'FL',
    structure_air_conditioning_type: 'Central air',
    structure_architecture_type: 'Modern',
    structure_basement_type: 'Finished Basement',
    structure_baths: 4,
    structure_beds_count: 4,
    structure_condition: 'New',
    structure_construction_type: 'Concrete',
    structure_effective_year_built: '\'-1',
    structure_exterior_wall_type: 'Concrete',
    structure_fireplaces: 1,
    structure_flooring_types: [
      {
        S: 'Marble',
      },
    ],
    structure_foundation_type: 'Concrete Slab',
    structure_heating_type: 'Central',
    structure_parking_spaces_count: '\'-1',
    structure_parking_type: 'Parking 1',
    structure_partial_baths_count: 0,
    structure_roof_material_type: 'Concrete',
    structure_roof_style_type: 'Concrete',
    structure_stories: 2,
    structure_total_area_sq_ft: '\'-1',
    structure_units_count: 1,
    structure_year_built: 2006,
    taxes: [
      {
        M: {
          year: {
            N: '2019',
          },
          amount: {
            N: '11469',
          },
        },
      },
    ],
    token_id: 602,
    token_price: 49.56842,
    token_smart_contract_url:
      'https://mumbai.polygonscan.com/address/0x6aa43165f4664a5e7c69678a9865e280162cf31f',
    tokens_on_hold: 0,
    tokens_remaining: 22780,
    tokens_remaining_blockchain: '',
    tokens_sold: 20,
    total_investments: 1108000,
    total_number_of_tokens: 22800,
    updated_at: '02-01-2023 15:36:04',
    userId: 'cc8c7284-ecbe-4ff4-af3b-d0facce0f3cf',
    utilities: 6000,
    valuation_forecast_standard_deviation: '\'-1',
    valuation_high: '\'-1',
    valuation_low: '\'-1',
    valuation_value: '\'-1',
    youtube_link:
      'https://mumbai.polygonscan.com/address/0x6aa43165f4664a5e7c69678a9865e280162cf31f',
    zip: 33647,
  },
  {
    pk: '#RE#400002a7-da9f-43ef-8926-b8e440e6adf5',
    sk: '#PROP',
    add: '4910 Ebensburg Dr',
    additional_perks: 'Test the numbers',
    address_city: 'Tampa',
    address_state: 'FL',
    fullAddress: '4910 Ebensburg Dr',
    address_zipCode: 33647,
    asset_price: 382000,
    city: 'Tampa',
    closing_cost: 9075,
    closing_date: '11-03-2023 15:08:23',
    company_name: '608 S 63rd St TPA LLC',
    expected_gross_rent_per_property: 92700,
    expected_gross_roi: 14.33459,
    expected_net_rent_per_property: 52438,
    expected_net_roi: 8.10871,
    expected_reserve_funds: 6000,
    expenses: 40262,
    gsi1_pk: '#USER#8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121',
    gsi1_sk: '#RE#400002a7-da9f-43ef-8926-b8e440e6adf5',
    gsi2_pk: '#4910 EBENSBURG DR#TAMPA#FL#33647',
    insurance: 3078,
    listing_price: 646687.6,
    maintenance_expense: 2781,
    maintenance_expense_in_percentage: 3,
    meta_land_revenue_stream: 'meta land revenue stream',
    meta_link:
      'https://www.zillow.com/homes/4910-Ebensburg-Dr-Tampa,-FL-33647_rb/44924581_zpid/',
    net_rent_per_token: 4.03,
    offering_memorandum_date: '11-01-2022 15:08:23',
    parcel_area_acres: 1,
    parcel_area_sq_ft: 1650,
    parcel_building_count: 1,
    parcel_county_land_use_code: 'RC001',
    parcel_county_land_use_description: 'Single Family',
    parcel_county_name: 'Hillsborough',
    parcel_depth_ft: '\'-1',
    parcel_frontage_ft: '\'-1',
    parcel_municipality: 'Hillsborough',
    parcel_subdivision: 'Brandon',
    parcel_zoning: 'RC001',
    platform_fees: 1854,
    platform_list_fees_in_percentage: 4,
    platform_listing_fees: 24872.600000000002,
    property_description: 'Test the numbers',
    property_mgmt_fees: 19,
    property_mgt_fees: 17613,
    property_taxes: 4376,
    re_id: '400002a7-da9f-43ef-8926-b8e440e6adf5',
    renovation_costs: 224740,
    rent_processing_fees: 2,
    state: 'FL',
    structure_air_conditioning_type: 'Central',
    structure_architecture_type: 'Modern',
    structure_basement_type: 'No Basement',
    structure_baths: 3,
    structure_beds_count: 3,
    structure_condition: 'New',
    structure_construction_type: 'Concrete',
    structure_effective_year_built: '\'-1',
    structure_exterior_wall_type: 'Concrete',
    structure_fireplaces: 0,
    structure_flooring_types: [
      {
        S: 'Wood',
      },
    ],
    structure_foundation_type: 'Concrete Slab',
    structure_heating_type: 'Central',
    structure_parking_spaces_count: 8,
    structure_parking_type: 'Parking 1',
    structure_partial_baths_count: 8,
    structure_roof_material_type: 'Shingle',
    structure_roof_style_type: 'Shingle',
    structure_stories: 1,
    structure_total_area_sq_ft: '\'-1',
    structure_units_count: 1,
    structure_year_built: 2001,
    taxes: [
      {
        M: {
          year: {
            N: '2021',
          },
          amount: {
            N: '4376',
          },
        },
      },
    ],
    token_id: 101,
    token_price: 49.7452,
    token_smart_contract_url: '0xD4D9e01d0Af297EDBA3b30E9797e17E93a651437',
    tokens_on_hold: 0,
    tokens_remaining: 13000,
    tokens_remaining_blockchain: '',
    tokens_sold: 0,
    total_investments: 621815,
    total_number_of_tokens: 13000,
    updated_at: '11-23-2022 10:42:19',
    userId: '8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121',
    utilities: 10560,
    valuation_forecast_standard_deviation: '\'-1',
    valuation_high: '\'-1',
    valuation_low: '\'-1',
    valuation_value: '\'-1',
    youtube_link: 'https://www.youtube.com/',
    zip: 33647,
  },
  {
    pk: '#RE#43528b33-7153-4ec9-bc69-53684f1f2b3b',
    sk: '#PROP',
    add: '18021 Malakai Isle Dr, Tampa, FL 33647',
    additional_perks: 'test1',
    address_city: 'Tampa',
    address_state: 'FL',
    fullAddress: '18021 Malakai Isle Dr, Tampa, FL 33647',
    address_zipCode: 33647,
    asset_price: 874000,
    city: 'Tampa',
    closing_cost: 15000,
    closing_date: '01-31-2023 00:00:00',
    company_name: '18021 Malakai Isle Dr TPA LLC 1',
    expected_gross_rent_per_property: 150000,
    expected_gross_roi: 16.33987,
    expected_net_rent_per_property: 84520,
    expected_net_roi: 9.20697,
    expected_reserve_funds: 6000,
    expenses: 65480,
    gsi1_pk: '#USER#8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121',
    gsi1_sk: '#RE#43528b33-7153-4ec9-bc69-53684f1f2b3b',
    gsi2_pk: '#18021 MALAKAI ISLE DR, TAMPA, FL 33647#TAMPA#FL#33647',
    insurance: 6000,
    listing_price: 918000,
    maintenance_expense: 4500,
    maintenance_expense_in_percentage: 3,
    meta_land_revenue_stream: 'meta land revenue stream',
    meta_link: 'https://matterport.com/',
    net_rent_per_token: 4.59,
    offering_memorandum_date: '10-31-2022 00:00:00',
    parcel_area_acres: 7405,
    parcel_area_sq_ft: 7405,
    parcel_building_count: 10,
    parcel_county_land_use_code: 'R001',
    parcel_county_land_use_description: 'Single Family',
    parcel_county_name: 'pasco',
    parcel_depth_ft: '\'-1',
    parcel_frontage_ft: 4,
    parcel_municipality: 'pasco',
    parcel_subdivision: 'pasco',
    parcel_zoning: 'R001',
    platform_fees: 3000,
    platform_list_fees_in_percentage: 2,
    platform_listing_fees: 18000,
    property_description: 'test1',
    property_mgmt_fees: 19,
    property_mgt_fees: 28500,
    property_taxes: 17480,
    re_id: '43528b33-7153-4ec9-bc69-53684f1f2b3b',
    renovation_costs: 5000,
    rent_processing_fees: 2,
    state: 'FL',
    structure_air_conditioning_type: 'central',
    structure_architecture_type: 'modern',
    structure_basement_type: 'No Basement',
    structure_baths: 5,
    structure_beds_count: 5,
    structure_condition: 'good',
    structure_construction_type: 'Wood frame',
    structure_effective_year_built: '\'-1',
    structure_exterior_wall_type: 'cement',
    structure_fireplaces: 'yes',
    structure_flooring_types: [
      {
        S: 'Marbel',
      },
    ],
    structure_foundation_type: 'Wood',
    structure_heating_type: 'heating',
    structure_parking_spaces_count: 10,
    structure_parking_type: 'Parking 1',
    structure_partial_baths_count: 10,
    structure_roof_material_type: 'Tile',
    structure_roof_style_type: 'Tile',
    structure_stories: 2,
    structure_total_area_sq_ft: '\'-1',
    structure_units_count: 2,
    structure_year_built: 1992,
    taxes: [
      {
        M: {
          year: {
            N: '2021',
          },
          amount: {
            N: '17480',
          },
        },
      },
    ],
    token_id: 603,
    token_price: 49.8913,
    token_smart_contract_url:
      'https://mumbai.polygonscan.com/address/0x6aa43165f4664a5e7c69678a9865e280162cf31f',
    tokens_on_hold: 3,
    tokens_remaining: 18283,
    tokens_remaining_blockchain: 18305,
    tokens_sold: 114,
    total_investments: 900000,
    total_number_of_tokens: 18400,
    updated_at: '03-13-2023 12:46:04',
    userId: '8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121',
    utilities: 6000,
    valuation_forecast_standard_deviation: '\'-1',
    valuation_high: '\'-1',
    valuation_low: '\'-1',
    valuation_value: '\'-1',
    youtube_link: 'https://www.youtube.com/',
    zip: 33647,
  },
  {
    pk: '#RE#5d0efc89-f79a-438b-8dd0-93f046141dea',
    sk: '#PROP',
    add: 'Trenton 31',
    additional_perks: 'Swimming pool',
    address_city: 'George',
    address_state: 'GA',
    fullAddress: 'Trenton 31',
    address_zipCode: 1170,
    asset_price: 10000,
    city: 'George',
    closing_cost: 1000,
    closing_date: '02-24-2023 11:21:51',
    company_name: 'New Company ',
    expected_gross_rent_per_property: 2200,
    expected_gross_roi: 17.81377,
    expected_net_rent_per_property: 1438,
    expected_net_roi: 11.64372,
    expected_reserve_funds: 800,
    expenses: 762,
    gsi1_pk: '#USER#1d2cff84-61d5-424f-ba0d-8ebe47f151e9',
    gsi1_sk: '#RE#5d0efc89-f79a-438b-8dd0-93f046141dea',
    gsi2_pk: '#TRENTON 31#GEORGE#GA#1170',
    insurance: 250,
    listing_price: 12350,
    maintenance_expense: 44,
    maintenance_expense_in_percentage: 2,
    meta_land_revenue_stream: 'meta land revenue stream',
    meta_link: 'https://www.youtube.com/@3Blocks_io',
    net_rent_per_token: 3.6,
    offering_memorandum_date: '02-24-2023 11:21:51',
    parcel_area_acres: 1,
    parcel_area_sq_ft: 2,
    parcel_building_count: 2,
    parcel_county_land_use_code: '4RR',
    parcel_county_land_use_description: 'Apartment',
    parcel_county_name: 'Georgetown',
    parcel_depth_ft: '\'-1',
    parcel_frontage_ft: 1,
    parcel_municipality: 'Municipal',
    parcel_subdivision: 'New Neighborhood',
    parcel_zoning: 'Zone',
    platform_fees: 44,
    platform_list_fees_in_percentage: 150,
    platform_listing_fees: 150,
    property_description: 'New and ultra modern',
    property_mgmt_fees: 2,
    property_mgt_fees: 44,
    property_taxes: 200,
    re_id: '5d0efc89-f79a-438b-8dd0-93f046141dea',
    renovation_costs: 400,
    rent_processing_fees: 2,
    state: 'GA',
    structure_air_conditioning_type: 'Cool Market',
    structure_architecture_type: 'Cool Arch',
    structure_basement_type: 'Finished Basement',
    structure_baths: 2,
    structure_beds_count: 2,
    structure_condition: 'New Condition',
    structure_construction_type: 'Concrete',
    structure_effective_year_built: '\'-1',
    structure_exterior_wall_type: 'Modern',
    structure_fireplaces: 'Ancient',
    structure_flooring_types: [
      {
        S: 'Wood',
      },
    ],
    structure_foundation_type: 'Wood',
    structure_heating_type: 'No Heating',
    structure_parking_spaces_count: 1,
    structure_parking_type: 'Parking 1',
    structure_partial_baths_count: 1,
    structure_roof_material_type: 'Tiles',
    structure_roof_style_type: 'Patterned',
    structure_stories: 1,
    structure_total_area_sq_ft: '\'-1',
    structure_units_count: 2,
    structure_year_built: 1998,
    taxes: [
      {
        M: {
          year: {
            N: '1990',
          },
          amount: {
            N: '301',
          },
        },
      },
    ],
    token_id: 111,
    token_price: 30.875,
    token_smart_contract_url: 'https://www.youtube.com/@3Blocks_io',
    tokens_on_hold: '',
    tokens_remaining: '',
    tokens_remaining_blockchain: '',
    tokens_sold: '',
    total_investments: 12200,
    total_number_of_tokens: 400,
    updated_at: '02-17-2023 11:07:14',
    userId: '1d2cff84-61d5-424f-ba0d-8ebe47f151e9',
    utilities: 180,
    valuation_forecast_standard_deviation: '\'-1',
    valuation_high: '\'-1',
    valuation_low: '\'-1',
    valuation_value: '\'-1',
    youtube_link: 'https://www.youtube.com/@3Blocks_io',
    zip: 1170,
  },
  {
    pk: '#RE#336f21a3-5b0a-4199-ad15-05d5119ee329',
    sk: '#PROP',
    add: '608 S 63rd Street',
    additional_perks:
      'Owners will be able to rent the property with additional 15% discount.\\nOwners will be able to showcase their NFTs in metaverse, facebook, Instagram etc.',
    address_city: 'Tampa',
    address_state: 'FL',
    fullAddress: '608 S 63rd Street',
    address_zipCode: 33619,
    asset_price: 382000,
    city: 'Tampa',
    closing_cost: 9075.29,
    closing_date: '03-31-2023 04:42:46',
    company_name: '608 S 63rd St TPA LLC',
    expected_gross_rent_per_property: 92700,
    expected_gross_roi: 14.71,
    expected_net_rent_per_property: 52438,
    expected_net_roi: 8.32,
    expected_reserve_funds: 9184,
    expenses: 40262,
    gsi1_pk: '#USER#8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121',
    gsi1_sk: '#RE#336f21a3-5b0a-4199-ad15-05d5119ee329',
    gsi2_pk: '#608 S 63RD STREET#TAMPA#FL#33619',
    insurance: 3078,
    listing_price: 630000.05,
    maintenance_expense: 2781,
    maintenance_expense_in_percentage: 3,
    meta_land_revenue_stream: 'meta land revenue stream',
    meta_link: 'https://youtu.be/SYxoBjf_8YE',
    net_rent_per_token: 4.16,
    offering_memorandum_date: '11-16-2022 04:42:46',
    parcel_area_acres: 1,
    parcel_area_sq_ft: 1344,
    parcel_building_count: 1,
    parcel_county_land_use_code: 'R001',
    parcel_county_land_use_description: 'Single Family',
    parcel_county_name: 'Hillsborough',
    parcel_depth_ft: '\'-1',
    parcel_frontage_ft: '\'-1',
    parcel_municipality: 'Hillsborough',
    parcel_subdivision: 'Brandon',
    parcel_zoning: 'R001',
    platform_fees: 927,
    platform_list_fees_in_percentage: 4,
    platform_listing_fees: 5000,
    property_description:
      'https://abnb.me/yCFCe460Zub\\n\\nThis modern and luxurious home is Fully fenced in with private Gate entry , close to everything, which will make your visit to Tampa very special. You can enjoy cooking at the outdoor kitchen, well designed working spaces , with high speed internet. hangout at the spacious patio and deck area, Play pool/Outdoor games and kids can enjoy the cozy treehouse on the property.\\n\\nThis property has 3 bedrooms and 3 bathrooms in the main house and there is a bedroom in the treehouse with a queen bed.\\n\\nBedroom 1 - king bed and attached bathroom\\nBedroom 2 - king bed and attached bathroom\\nBedroom 3 - king bed and common full bath next to the room.\\nBedroom 4 - queen bed in the treehouse.\\n\\n-Pool Table\\n-Jacuzzi in Bathroom\\n-Outdoor Kitchen with Gas grill\\n-Laundry Room\\n- Outdoor Bar area with refrigerator\\n- Plenty of parking\\n-Gated property\\n\\nFully renovated kitchen with oven,Fully equipped\\nMicrowave\\nBlender\\ncutting boards\\nSet of sharp knives\\n1 dishwasher\\nPlenty of pots/pans/cooking utensils\\nWine glasses, beer glasses,\\n\\nLAUNDRY ROOM – House has built-in High-Efficiency front loading washer and dryer, ironing board, iron, laundry basket.\\nGuest access\\nGuests have access to the entire property.',
    property_mgmt_fees: 20,
    property_mgt_fees: 18540,
    property_taxes: 4376,
    re_id: '336f21a3-5b0a-4199-ad15-05d5119ee329',
    renovation_costs: 224740.76,
    rent_processing_fees: 1,
    state: 'FL',
    structure_air_conditioning_type: 'Central',
    structure_architecture_type: 'Modern',
    structure_basement_type: 'No Basement',
    structure_baths: 3,
    structure_beds_count: 3,
    structure_condition: 'New',
    structure_construction_type: 'Concrete',
    structure_effective_year_built: '\'-1',
    structure_exterior_wall_type: 'Concrete',
    structure_fireplaces: 0,
    structure_flooring_types: [
      {
        S: 'Ceramic',
      },
    ],
    structure_foundation_type: 'Concrete Slab',
    structure_heating_type: 'Central',
    structure_parking_spaces_count: 8,
    structure_parking_type: 'Parking 1',
    structure_partial_baths_count: 8,
    structure_roof_material_type: 'Shingle',
    structure_roof_style_type: 'Shingle',
    structure_stories: 1,
    structure_total_area_sq_ft: '\'-1',
    structure_units_count: 1,
    structure_year_built: 2008,
    taxes: [
      {
        M: {
          year: {
            N: '2021',
          },
          amount: {
            N: '4376',
          },
        },
      },
    ],
    token_id: 603,
    token_price: 49.99,
    token_smart_contract_url: '0xD4D9e01d0Af297EDBA3b30E9797e17E93a651437',
    tokens_on_hold: 0,
    tokens_remaining: 12496,
    tokens_remaining_blockchain: 18312,
    tokens_sold: 104,
    total_investments: 624999,
    total_number_of_tokens: 12600,
    updated_at: '02-18-2023 11:58:04',
    userId: '8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121',
    utilities: 10560,
    valuation_forecast_standard_deviation: '\'-1',
    valuation_high: '\'-1',
    valuation_low: '\'-1',
    valuation_value: '\'-1',
    youtube_link: 'https://youtu.be/SYxoBjf_8YE',
    zip: 33619,
  },
]
