export const digitalBonds = [
  /* {
    companyName: 'Ondo',
    assetName: 'Ondo Short-Term Investment Grade Bond Fund',
    fundMgmtFees: '0.15%',
    additionalFees: '0.15%',
    estYieldToMaturity: '5.69%',
    day30SecYield: '4.93%',
    totalAssets: '$8.4b',
    liquidity: '$86m of daily trading volume',
    weightedAvgMaturity: '0.62 years',
    standardDeviation: '2.02%',
    tokenName: 'OSTB',
    smartContract: '',
    productPage: 'https://ondo.finance/ostb',
    factSheet:
      'https://www.pimco.com/handlers/displaydocument.ashx?
      c=72201R833&wd=Fact%20Sheet&fn=ETF%20PIMCO%20Enhanced%20Short%20Maturity%20Active%20ETF%20FS.pdf&id=
      oHPxmWbgcuUnezuGymJNPEfhGYzZZovumHqXq1BiBxPxKlkp7LG0CKuUDK
      eFRwEWKpcnEILwX2L9dm553MnimdFkQWMpUxWUtSkZJdtHhcdWc4%2bQ
      YITBe2L4cDi2DAS4vSXakbWPvxys5aHr1RixUrPTDSIpgIpYwCIgFeuJhNR
      M8NWnukq5tZn6UEV4TR0I3kcHnx%2f0YBe8GDab0AhWmM022OUxtu%2b7W
      5lEZlII%2b9RM6Ud4xSvDoktO6oh8hSZDwo5yaY8e9jaHYPyWUxUl57fpw4
      %2fP9NexIG3EinXI7uuE43eK%2fZ6eVhOWJQlEjyWqAJDoLklBIae%2fzxub
      XWMI0RkAalsfyynMRmOKP8zkxT5YpdDLgwN%2ferLB69xRB4vr071Le0UYK7a
      5kGSyhMq4aQkFMldtQRhuF1UCH%2fD2rfRa7GvjLHi7H0kHJhht1vOIxUcfWiU
      VuUMRCitcZZcst6tFj5Vz9ZwkWKfwZgwZ2kY%3d',
  },
  {
    companyName: 'Ondo',
    assetName: 'Ondo Short-Term US Government Bond Fund',
    fundMgmtFees: '0.15%',
    additionalFees: '0.15%',
    estYieldToMaturity: '4.65%',
    day30SecYield: '4.58%',
    totalAssets: '$23.43b',
    liquidity: '$463m of daily trading volume',
    weightedAvgMaturity: '0.28 years',
    standardDeviation: '0.48%',
    tokenName: 'OUSG',
    smartContract: '0x1b19c19393e2d034d8ff31ff34c81252fcbbee92',
    productPage: 'https://ondo.finance/ousg',
    factSheet:
      'https://www.ishares.com/us/literature/fact-sheet/shv-ishares-short-treasury-bond-etf-fund-fact-sheet-en-us.pdf',
  },
  {
    companyName: 'Ondo',
    assetName: 'Ondo High Yield Corporate Bond Fund',
    fundMgmtFees: '0.15%',
    additionalFees: '0.15%',
    estYieldToMaturity: '8.40%',
    day30SecYield: '8.11%',
    totalAssets: '$12.26b',
    liquidity: '$3.8b of daily trading volume',
    weightedAvgMaturity: '4.98 years',
    standardDeviation: '11.15%',
    tokenName: 'OHYG',
    smartContract: '',
    productPage: 'https://ondo.finance/ohyg',
    factSheet:
      'https://www.ishares.com/us/literature/fact-sheet/hyg-ishares-iboxx-high-yield-corporate-bond-etf-fund-fact-sheet-en-us.pdf',
  }, */
  {
    companyName: 'Cytus Finance',
    assetName: 'US Treasury Bill Pool',
    fundMgmtFees: '',
    additionalFees: '',
    estYieldToMaturity: '4.49%',
    day30SecYield: '',
    totalAssets: '5,492.086914',
    liquidity: '',
    weightedAvgMaturity: '',
    standardDeviation: '',
    tokenName: 'CTB1',
    smartContract: '0x6e5D9c5526Ab88BB302E99Beb3e62c237217D629',
    productPage: 'https://app.cytus.finance/project/0x003',
    factSheet: '',
  },
  {
    companyName: 'Cytus Finance',
    assetName: 'US Real Estate Pool - Single Asset',
    fundMgmtFees: '',
    additionalFees: '',
    estYieldToMaturity: '7.11%',
    day30SecYield: '',
    totalAssets: '888.055624',
    liquidity: '',
    weightedAvgMaturity: '',
    standardDeviation: '',
    tokenName: 'CRE1',
    smartContract: '0x5c3a7cd8874fDcF8E8646BD58Ad57d281802D893',
    productPage: 'https://app.cytus.finance/project/0x002',
    factSheet: '',
  },
  {
    companyName: 'Cytus Finance',
    assetName: 'Multi-family Condos Sunset Park, NY I',
    fundMgmtFees: '',
    additionalFees: '',
    estYieldToMaturity: '6%',
    day30SecYield: '',
    totalAssets: '14,020',
    liquidity: '',
    weightedAvgMaturity: '',
    standardDeviation: '',
    tokenName: 'CTS1',
    smartContract: '0x79D8477481020DACcd2A216291dE2523e82b6D00',
    productPage: 'https://app.cytus.finance/project/0x000',
    factSheet: '',
  },
  {
    companyName: 'Cytus Finance',
    assetName: 'Multi-family Condos Sunset Park, NY II',
    fundMgmtFees: '',
    additionalFees: '',
    estYieldToMaturity: '6%',
    day30SecYield: '',
    totalAssets: '200,000',
    liquidity: '',
    weightedAvgMaturity: '',
    standardDeviation: '',
    tokenName: 'CTS2',
    smartContract: '0x481A790CF093A0cd9D6486e6a19aF93b221c6b90',
    productPage: 'https://app.cytus.finance/project/0x001',
    factSheet: '',
  },
]
