const loftInputs = [
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty AI',
      tokenId: 237267329,
      totalTokens: 10000001,
      tokenName: 'Lofty AI',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 917 Pawnee LFTY0001',
      tokenId: 237913743,
      totalTokens: 2160,
      tokenName: 'Lofty 917 Pawnee LFTY0001',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4661 Berta Rd',
      tokenId: 257805044,
      totalTokens: 1970,
      tokenName: 'Lofty 4661 Berta Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3557 Carrington Rd',
      tokenId: 276461096,
      totalTokens: 2140,
      tokenName: 'Lofty 3557 Carrington Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 16171 Ilene St',
      tokenId: 284090786,
      totalTokens: 2762,
      tokenName: 'Lofty 16171 Ilene St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 2337 Greenvale Rd',
      tokenId: 287504952,
      totalTokens: 1959,
      tokenName: 'Lofty 2337 Greenvale Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4920 E 110th St',
      tokenId: 306034694,
      totalTokens: 2509,
      tokenName: 'Lofty 4920 E 110th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4318 Clybourne Ave',
      tokenId: 307329013,
      totalTokens: 4819,
      tokenName: 'Lofty 4318 Clybourne Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3514 W 123rd St',
      tokenId: 310079703,
      totalTokens: 2366,
      tokenName: 'Lofty 3514 W 123rd St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 14720 Ohio Ave',
      tokenId: 310928550,
      totalTokens: 2432,
      tokenName: 'Lofty 14720 Ohio Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4312 E 162nd St',
      tokenId: 312414178,
      totalTokens: 2157,
      tokenName: 'Lofty 4312 E 162nd St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 9634 S Green St',
      tokenId: 317188185,
      totalTokens: 3367,
      tokenName: 'Lofty 9634 S Green St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 18474 Glenmore St',
      tokenId: 324785039,
      totalTokens: 2784,
      tokenName: 'Lofty 18474 Glenmore St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 16713 Lotus Dr',
      tokenId: 330057448,
      totalTokens: 2344,
      tokenName: 'Lofty 16713 Lotus Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4245 E 177th Pl',
      tokenId: 331477055,
      totalTokens: 2454,
      tokenName: 'Lofty 4245 E 177th Pl',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 251 Wachtel Ave',
      tokenId: 331601581,
      totalTokens: 2839,
      tokenName: 'Lofty 251 Wachtel Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 329 Stoneham Rd',
      tokenId: 339977421,
      totalTokens: 2223,
      tokenName: 'Lofty 329 Stoneham Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 5003 Deneen Dr',
      tokenId: 341164928,
      totalTokens: 2564,
      tokenName: 'Lofty 5003 Deneen Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 333 Illinois Ave',
      tokenId: 343527910,
      totalTokens: 3889,
      tokenName: 'Lofty 333 Illinois Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3905 E 189th St',
      tokenId: 344858966,
      totalTokens: 2352,
      tokenName: 'Lofty 3905 E 189th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4131 Wright Ave',
      tokenId: 347948733,
      totalTokens: 2493,
      tokenName: 'Lofty 4131 Wright Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3535 Debby Dr',
      tokenId: 349258461,
      totalTokens: 2220,
      tokenName: 'Lofty 3535 Debby Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3429 W 8th St',
      tokenId: 350604095,
      totalTokens: 3452,
      tokenName: 'Lofty 3429 W 8th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3133 Estes St',
      tokenId: 351807576,
      totalTokens: 3892,
      tokenName: 'Lofty 3133 Estes St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 6914 Polonia Ave',
      tokenId: 354715064,
      totalTokens: 2242,
      tokenName: 'Lofty 6914 Polonia Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1380 Kimball Cv',
      tokenId: 356682443,
      totalTokens: 3208,
      tokenName: 'Lofty 1380 Kimball Cv',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 19416 Winston St',
      tokenId: 357651871,
      totalTokens: 2352,
      tokenName: 'Lofty 19416 Winston St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3976 Stillwood Dr',
      tokenId: 359624611,
      totalTokens: 2792,
      tokenName: 'Lofty 3976 Stillwood Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 7757 Lamphere St',
      tokenId: 360767798,
      totalTokens: 2141,
      tokenName: 'Lofty 7757 Lamphere St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3038 Sinclair St',
      tokenId: 365261108,
      totalTokens: 3032,
      tokenName: 'Lofty 3038 Sinclair St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3561 Daleford Rd',
      tokenId: 367097138,
      totalTokens: 4220,
      tokenName: 'Lofty 3561 Daleford Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 2724 Chatsworth St',
      tokenId: 368464732,
      totalTokens: 1718,
      tokenName: 'Lofty 2724 Chatsworth St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 11400 Linnet Ave',
      tokenId: 370245186,
      totalTokens: 3012,
      tokenName: 'Lofty 11400 Linnet Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1039 Mt Vernon Rd',
      tokenId: 371435087,
      totalTokens: 2198,
      tokenName: 'Lofty 1039 Mt Vernon Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 445 Lipford St',
      tokenId: 375201811,
      totalTokens: 2922,
      tokenName: 'Lofty 445 Lipford St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1677 Walker Ave',
      tokenId: 377975532,
      totalTokens: 4222,
      tokenName: 'Lofty 1677 Walker Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 10917 Fidelity Ave',
      tokenId: 385007719,
      totalTokens: 3254,
      tokenName: 'Lofty 10917 Fidelity Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4326 E 175th St',
      tokenId: 386183165,
      totalTokens: 1934,
      tokenName: 'Lofty 4326 E 175th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 9919 S Oglesby Ave',
      tokenId: 387809238,
      totalTokens: 3538,
      tokenName: 'Lofty 9919 S Oglesby Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3878 Windermere Rd',
      tokenId: 393401013,
      totalTokens: 2792,
      tokenName: 'Lofty 3878 Windermere Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 5630 Morgan Ford Rd',
      tokenId: 394602287,
      totalTokens: 2990,
      tokenName: 'Lofty 5630 Morgan Ford Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 29172 Oakwood St',
      tokenId: 395813328,
      totalTokens: 2176,
      tokenName: 'Lofty 29172 Oakwood St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 7014 Raymond Ave',
      tokenId: 397955540,
      totalTokens: 2297,
      tokenName: 'Lofty 7014 Raymond Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 6422 Mount Ave',
      tokenId: 400382442,
      totalTokens: 2176,
      tokenName: 'Lofty 6422 Mount Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 5541 S Peoria St',
      tokenId: 404014477,
      totalTokens: 5728,
      tokenName: 'Lofty 5541 S Peoria St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 15555 Millard Ave',
      tokenId: 406662616,
      totalTokens: 3208,
      tokenName: 'Lofty 15555 Millard Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1123 Hudson Rd',
      tokenId: 408317316,
      totalTokens: 2880,
      tokenName: 'Lofty 1123 Hudson Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1456 W 85th St',
      tokenId: 411182963,
      totalTokens: 4662,
      tokenName: 'Lofty 1456 W 85th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 10917 St Mark Ave',
      tokenId: 411484181,
      totalTokens: 2748,
      tokenName: 'Lofty 10917 St Mark Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 12808 Gruss Ave',
      tokenId: 415479257,
      totalTokens: 2330,
      tokenName: 'Lofty 12808 Gruss Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 8143 South Sangamon St',
      tokenId: 415780733,
      totalTokens: 7021,
      tokenName: 'Lofty 8143 South Sangamon St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3024 W 103rd St',
      tokenId: 421233661,
      totalTokens: 1824,
      tokenName: 'Lofty 3024 W 103rd St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 2094 W 34th Place',
      tokenId: 423834123,
      totalTokens: 4266,
      tokenName: 'Lofty 2094 W 34th Place',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 9583 Pagewood Ave',
      tokenId: 428719354,
      totalTokens: 2415,
      tokenName: 'Lofty 9583 Pagewood Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 9423 Denison Ave',
      tokenId: 428942742,
      totalTokens: 3672,
      tokenName: 'Lofty 9423 Denison Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 12028 Wade Park Ave',
      tokenId: 433935394,
      totalTokens: 4442,
      tokenName: 'Lofty 12028 Wade Park Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 8708 Willard Ave',
      tokenId: 437070179,
      totalTokens: 2638,
      tokenName: 'Lofty 8708 Willard Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 20413 Kingsville St',
      tokenId: 438690404,
      totalTokens: 2174,
      tokenName: 'Lofty 20413 Kingsville St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1388 Penhurst Rd',
      tokenId: 440238741,
      totalTokens: 1486,
      tokenName: 'Lofty 1388 Penhurst Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1278 E 187th St',
      tokenId: 443323227,
      totalTokens: 1717,
      tokenName: 'Lofty 1278 E 187th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 7542 & 7656 S Colfax Ave',
      tokenId: 446545048,
      totalTokens: 16168,
      tokenName: 'Lofty 7542 & 7656 S Colfax Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 428 Cross St',
      tokenId: 449485006,
      totalTokens: 4882,
      tokenName: 'Lofty 428 Cross St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3139 West Blvd',
      tokenId: 451431994,
      totalTokens: 4486,
      tokenName: 'Lofty 3139 West Blvd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 25 Circle Dr',
      tokenId: 459493039,
      totalTokens: 2922,
      tokenName: 'Lofty 25 Circle Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3031 W Flournoy St',
      tokenId: 460608994,
      totalTokens: 6837,
      tokenName: 'Lofty 3031 W Flournoy St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3834 W Polk St',
      tokenId: 462627255,
      totalTokens: 9027,
      tokenName: 'Lofty 3834 W Polk St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 665 Chapman St',
      tokenId: 465553355,
      totalTokens: 4242,
      tokenName: 'Lofty 665 Chapman St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 755 Robinwood Dr',
      tokenId: 468433605,
      totalTokens: 2660,
      tokenName: 'Lofty 755 Robinwood Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 7704 Mallard Dr',
      tokenId: 471808654,
      totalTokens: 1968,
      tokenName: 'Lofty 7704 Mallard Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3435-3437 Alberta St',
      tokenId: 527575200,
      totalTokens: 5386,
      tokenName: 'Lofty 3435-3437 Alberta St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3106 Quiet Lane',
      tokenId: 531777911,
      totalTokens: 2153,
      tokenName: 'Lofty 3106 Quiet Lane',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3493 W 119th St',
      tokenId: 555868957,
      totalTokens: 2258,
      tokenName: 'Lofty 3493 W 119th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3634 Bosworth Rd',
      tokenId: 558143260,
      totalTokens: 10408,
      tokenName: 'Lofty 3634 Bosworth Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3178 W 41st & 9510 Silk',
      tokenId: 567114163,
      totalTokens: 3548,
      tokenName: 'Lofty 3178 W 41st & 9510 Silk',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3850 W 17th St',
      tokenId: 579451052,
      totalTokens: 3334,
      tokenName: 'Lofty 3850 W 17th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1845 W 48th St',
      tokenId: 581154878,
      totalTokens: 4430,
      tokenName: 'Lofty 1845 W 48th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1174 Tampa Ave',
      tokenId: 583495589,
      totalTokens: 1887,
      tokenName: 'Lofty 1174 Tampa Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1133 Bethany Ave',
      tokenId: 598341134,
      totalTokens: 1645,
      tokenName: 'Lofty 1133 Bethany Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1090 Diagonal Rd',
      tokenId: 602119108,
      totalTokens: 1797,
      tokenName: 'Lofty 1090 Diagonal Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 7411 Elton Ave',
      tokenId: 638273451,
      totalTokens: 2464,
      tokenName: 'Lofty 7411 Elton Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 7480 Halpin Dr',
      tokenId: 639641542,
      totalTokens: 2410,
      tokenName: 'Lofty 7480 Halpin Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 15711 Grovewood Ave',
      tokenId: 646502690,
      totalTokens: 4125,
      tokenName: 'Lofty 15711 Grovewood Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 14320 Granger Rd',
      tokenId: 648664981,
      totalTokens: 3079,
      tokenName: 'Lofty 14320 Granger Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 640 N Cicero Ave',
      tokenId: 649973549,
      totalTokens: 10207,
      tokenName: 'Lofty 640 N Cicero Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 656 E 126th St',
      tokenId: 651739129,
      totalTokens: 1722,
      tokenName: 'Lofty 656 E 126th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 2082 W 91st St',
      tokenId: 656876671,
      totalTokens: 2724,
      tokenName: 'Lofty 2082 W 91st St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 8201 Madison Ave',
      tokenId: 661277818,
      totalTokens: 9694,
      tokenName: 'Lofty 8201 Madison Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty Ohio 3 Property Package',
      tokenId: 664464508,
      totalTokens: 6762,
      tokenName: 'Lofty Ohio 3 Property Package',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1773 Ball Rd',
      tokenId: 670777243,
      totalTokens: 1931,
      tokenName: 'Lofty 1773 Ball Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 621 E Le Claire Rd',
      tokenId: 672810002,
      totalTokens: 49760,
      tokenName: 'Lofty 621 E Le Claire Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 809 Kenmore Blvd',
      tokenId: 684477003,
      totalTokens: 6076,
      tokenName: 'Lofty 809 Kenmore Blvd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 723 12th St',
      tokenId: 691139538,
      totalTokens: 2995,
      tokenName: 'Lofty 723 12th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 9902 Garfield Ave',
      tokenId: 692584955,
      totalTokens: 1836,
      tokenName: 'Lofty 9902 Garfield Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1015 Wycomb Dr',
      tokenId: 694067049,
      totalTokens: 3095,
      tokenName: 'Lofty 1015 Wycomb Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1432 Sara Ave',
      tokenId: 695242274,
      totalTokens: 1950,
      tokenName: 'Lofty 1432 Sara Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 10724 Gooding Avenue',
      tokenId: 697325251,
      totalTokens: 2501,
      tokenName: 'Lofty 10724 Gooding Avenue',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 12507 Astor Ave',
      tokenId: 701498055,
      totalTokens: 2453,
      tokenName: 'Lofty 12507 Astor Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 432 W Peebles Rd',
      tokenId: 702835587,
      totalTokens: 2032,
      tokenName: 'Lofty 432 W Peebles Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 254 Bowmanville St',
      tokenId: 706533341,
      totalTokens: 2108,
      tokenName: 'Lofty 254 Bowmanville St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1248 S Keeler Ave',
      tokenId: 708906045,
      totalTokens: 8780,
      tokenName: 'Lofty 1248 S Keeler Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 799 Stadelman Ave',
      tokenId: 710256863,
      totalTokens: 2391,
      tokenName: 'Lofty 799 Stadelman Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 918 Frederick Blvd',
      tokenId: 711241814,
      totalTokens: 1560,
      tokenName: 'Lofty 918 Frederick Blvd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3933 Walsh St',
      tokenId: 715111483,
      totalTokens: 2056,
      tokenName: 'Lofty 3933 Walsh St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 614 E 97th St',
      tokenId: 717117066,
      totalTokens: 2624,
      tokenName: 'Lofty 614 E 97th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 883 Alhambra Rd',
      tokenId: 721954274,
      totalTokens: 2501,
      tokenName: 'Lofty 883 Alhambra Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1848 Baldwin Ave',
      tokenId: 723519637,
      totalTokens: 2359,
      tokenName: 'Lofty 1848 Baldwin Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 5401 Odom Ave',
      tokenId: 739680855,
      totalTokens: 11877,
      tokenName: 'Lofty 5401 Odom Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4551 Sunny View Dr',
      tokenId: 754051439,
      totalTokens: 1950,
      tokenName: 'Lofty 4551 Sunny View Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3427 Sturdevant St',
      tokenId: 760111092,
      totalTokens: 2024,
      tokenName: 'Lofty 3427 Sturdevant St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1584 Hampton Rd',
      tokenId: 765000179,
      totalTokens: 1874,
      tokenName: 'Lofty 1584 Hampton Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 703 23rd Ave',
      tokenId: 768368477,
      totalTokens: 1783,
      tokenName: 'Lofty 703 23rd Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1106 29th Ave',
      tokenId: 769679594,
      totalTokens: 1868,
      tokenName: 'Lofty 1106 29th Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4183 E 146th St',
      tokenId: 770865636,
      totalTokens: 1939,
      tokenName: 'Lofty 4183 E 146th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3541 Oregon Ave',
      tokenId: 772180213,
      totalTokens: 10454,
      tokenName: 'Lofty 3541 Oregon Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1236 W 7th St',
      tokenId: 773336712,
      totalTokens: 1667,
      tokenName: 'Lofty 1236 W 7th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 209 E 13th St',
      tokenId: 774347071,
      totalTokens: 1559,
      tokenName: 'Lofty 209 E 13th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 3531 Oregon Ave',
      tokenId: 776845434,
      totalTokens: 5109,
      tokenName: 'Lofty 3531 Oregon Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 12627 Franklin Blvd',
      tokenId: 779159551,
      totalTokens: 6837,
      tokenName: 'Lofty 12627 Franklin Blvd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 615 Rose Ln',
      tokenId: 781289536,
      totalTokens: 1626,
      tokenName: 'Lofty 615 Rose Ln',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1234 Itin St',
      tokenId: 783214523,
      totalTokens: 6148,
      tokenName: 'Lofty 1234 Itin St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 26931 Shoreview Ave',
      tokenId: 784533078,
      totalTokens: 2684,
      tokenName: 'Lofty 26931 Shoreview Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 566 Nash St',
      tokenId: 785583551,
      totalTokens: 2071,
      tokenName: 'Lofty 566 Nash St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 296 Huntington Ave',
      tokenId: 790088226,
      totalTokens: 2051,
      tokenName: 'Lofty 296 Huntington Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 542 Sumner St',
      tokenId: 798651566,
      totalTokens: 2736,
      tokenName: 'Lofty 542 Sumner St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 13806 Coit Rd',
      tokenId: 813100557,
      totalTokens: 1971,
      tokenName: 'Lofty 13806 Coit Rd',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 142 13th St',
      tokenId: 813116645,
      totalTokens: 2770,
      tokenName: 'Lofty 142 13th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 9710 S Avenue L Ave',
      tokenId: 815075619,
      totalTokens: 10484,
      tokenName: 'Lofty 9710 S Avenue L Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 783 Leonard St',
      tokenId: 819609796,
      totalTokens: 1661,
      tokenName: 'Lofty 783 Leonard St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 4408 17th Ave',
      tokenId: 834658869,
      totalTokens: 1610,
      tokenName: 'Lofty 4408 17th Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 566 Sumner St',
      tokenId: 841565461,
      totalTokens: 2385,
      tokenName: 'Lofty 566 Sumner St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 8401 Lydia Ave',
      tokenId: 882856729,
      totalTokens: 3774,
      tokenName: 'Lofty 8401 Lydia Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 110 Gardengate Dr',
      tokenId: 886638002,
      totalTokens: 6645,
      tokenName: 'Lofty 110 Gardengate Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 927 Euclid Ave Apt 10',
      tokenId: 894817444,
      totalTokens: 9558,
      tokenName: 'Lofty 927 Euclid Ave Apt 10',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 2515 Coronet Dr',
      tokenId: 900942105,
      totalTokens: 3834,
      tokenName: 'Lofty 2515 Coronet Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1420 Brookhaven Dr',
      tokenId: 903033821,
      totalTokens: 6396,
      tokenName: 'Lofty 1420 Brookhaven Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 323 E 9th St',
      tokenId: 954185193,
      totalTokens: 2653,
      tokenName: 'Lofty 323 E 9th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1315 E 114th St',
      tokenId: 955551813,
      totalTokens: 2346,
      tokenName: 'Lofty 1315 E 114th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 594 Columbia Ave',
      tokenId: 960593591,
      totalTokens: 2473,
      tokenName: 'Lofty 594 Columbia Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1339 E 115th St',
      tokenId: 971778590,
      totalTokens: 2969,
      tokenName: 'Lofty 1339 E 115th St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 5133 Dresden Ave',
      tokenId: 977638343,
      totalTokens: 2329,
      tokenName: 'Lofty 5133 Dresden Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 6746 Westwood St',
      tokenId: 984814367,
      totalTokens: 1604,
      tokenName: 'Lofty 6746 Westwood St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 10157 Winkler Dr',
      tokenId: 1002765064,
      totalTokens: 1736,
      tokenName: 'Lofty 10157 Winkler Dr',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 127 Hausman St',
      tokenId: 1023334924,
      totalTokens: 1586,
      tokenName: 'Lofty 127 Hausman St',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty Edinburg Estate',
      tokenId: 1029073094,
      totalTokens: 10,
      tokenName: 'Lofty Edinburg Estate',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 16301 Glendale Ave',
      tokenId: 1029379725,
      totalTokens: 2325,
      tokenName: 'Lofty 16301 Glendale Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 8646 Ford Ave',
      tokenId: 1044033654,
      totalTokens: 2204,
      tokenName: 'Lofty 8646 Ford Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 11019 Essex Ave',
      tokenId: 1049889280,
      totalTokens: 1944,
      tokenName: 'Lofty 11019 Essex Ave',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 801 15th Street Unit 204',
      tokenId: 1071055319,
      totalTokens: 5763,
      tokenName: 'Lofty 801 15th Street Unit 204',
    },
  },
  {
    blockchain: {
      blockchainName: 'algorand',
      deployingAddress: 'LOFTYRITC3QUX6TVQBGT3BARKWAZDEB2TTJWYQMH6YITKNH7IOMWRLC7SA',
      transactionHash: '',
      tickerSymbol: 'Lofty 1033 Cedar Village Trl',
      tokenId: 1081594964,
      totalTokens: 5448,
      tokenName: 'Lofty 1033 Cedar Village Trl',
    },
  },
]
