const blocks_Data = {
    "pk": "#RE#43528b33-7153-4ec9-bc69-53684f1f2b3b",
    "sk": "#PROP",
    "add": "18021 Malakai Isle Dr, Tampa, FL 33647",
    "additional_perks": "test1",
    "address_city": "Tampa",
    "address_state": "FL",
    "address_streetAddress": "18021 Malakai Isle Dr, Tampa, FL 33647",
    "address_zipCode": 33647,
    "asset_price": 874000,
    "city": "Tampa",
    "closing_cost": 15000,
    "closing_date": "01-31-2023 00:00:00",
    "company_name": "18021 Malakai Isle Dr TPA LLC 1",
    "expected_gross_rent_per_property": 150000,
    "expected_gross_roi": 16.33987,
    "expected_net_rent_per_property": 84520,
    "expected_net_roi": 9.20697,
    "expected_reserve_funds": 6000,
    "expenses": 65480,
    "gsi1_pk": "#USER#8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121",
    "gsi1_sk": "#RE#43528b33-7153-4ec9-bc69-53684f1f2b3b",
    "gsi2_pk": "#18021 MALAKAI ISLE DR, TAMPA, FL 33647#TAMPA#FL#33647",
    "insurance": 6000,
    "listing_price": 918000,
    "maintenance_expense": 4500,
    "maintenance_expense_in_percentage": 3,
    "meta_land_revenue_stream": "meta land revenue stream",
    "meta_link": "https://matterport.com/",
    "net_rent_per_token": 4.59,
    "offering_memorandum_date": "10-31-2022 00:00:00",
    "parcel_area_acres": 7405,
    "parcel_area_sq_ft": 7405,
    "parcel_building_count": 10,
    "parcel_county_land_use_code": "R001",
    "parcel_county_land_use_description": "Single Family",
    "parcel_county_name": "pasco",
    "parcel_depth_ft": "'-1",
    "parcel_frontage_ft": 4,
    "parcel_municipality": "pasco",
    "parcel_subdivision": "pasco",
    "parcel_zoning": "R001",
    "platform_fees": 3000,
    "platform_list_fees_in_percentage": 2,
    "platform_listing_fees": 18000,
    "property_description": "test1",
    "property_mgmt_fees": 19,
    "property_mgt_fees": 28500,
    "property_taxes": 17480,
    "re_id": "43528b33-7153-4ec9-bc69-53684f1f2b3b",
    "renovation_costs": 5000,
    "rent_processing_fees": 2,
    "state": "FL",
    "structure_air_conditioning_type": "central",
    "structure_architecture_type": "modern",
    "structure_basement_type": "No Basement",
    "structure_baths": 5,
    "structure_beds_count": 5,
    "structure_condition": "good",
    "structure_construction_type": "Wood frame",
    "structure_effective_year_built": "'-1",
    "structure_exterior_wall_type": "cement",
    "structure_fireplaces": "yes",
    "structure_flooring_types": [
        {
            "S": "Marbel"
        }
    ],
    "structure_foundation_type": "Wood",
    "structure_heating_type": "heating",
    "structure_parking_spaces_count": 10,
    "structure_parking_type": "Parking 1",
    "structure_partial_baths_count": 10,
    "structure_roof_material_type": "Tile",
    "structure_roof_style_type": "Tile",
    "structure_stories": 2,
    "structure_total_area_sq_ft": "'-1",
    "structure_units_count": 2,
    "structure_year_built": 1992,
    "taxes": [
        {
            "M": {
                "year": {
                    "N": "2021"
                },
                "amount": {
                    "N": "17480"
                }
            }
        }
    ],
    "token_id": 603,
    "token_price": 49.8913,
    "token_smart_contract_url": "https://mumbai.polygonscan.com/address/0x6aa43165f4664a5e7c69678a9865e280162cf31f",
    "tokens_on_hold": 3,
    "tokens_remaining": 18283,
    "tokens_remaining_blockchain": 18305,
    "tokens_sold": 114,
    "total_investments": 900000,
    "total_number_of_tokens": 18400,
    "updated_at": "03-13-2023 12:46:04",
    "userId": "8c49e7fd-9258-4ab4-b7cd-4ae24fc4c121",
    "utilities": 6000,
    "valuation_forecast_standard_deviation": "'-1",
    "valuation_high": "'-1",
    "valuation_low": "'-1",
    "valuation_value": "'-1",
    "youtube_link": "https://www.youtube.com/",
    "zip": 33647
}

const newDataDB = {
    "pk": '#DRE#' + blocks_Data.re_id,
    "sk": "3blocks",
    companyName: '3blocks',
    contractAddress: '0x6aa43165f4664a5e7c69678a9865e280162cf31f',
    csv: {
        tokenPrice: blocks_Data.token_price || '',
        estROI: blocks_Data.expected_net_roi || '',
        platFormFees: blocks_Data.platform_fees || '',
        assetPrice: blocks_Data.asset_price || '',
        totalInverstment: blocks_Data.total_investments || '',
        fullAddress: blocks_Data.address_streetAddress,
        ...blocks_Data
    },
    "gsi1_pk": "#DRE#",
    "gsi1_sk": blocks_Data.add,
    "reId": blocks_Data.re_id,
}
