query getApplicantById($applicantId: String!){
    getApplicantById(applicantId: $applicantId){
        address{
            buildingName
            buildingNumber
            country
            flatNumber
            line1
            line2
            line3
            postcode
            state
            street
            subStreet
            town
        }
        createdAt
        deleteAt
        dob
        email
        firstName
        href
        id
        idNumbers{
            stateCode
            type
            value
        }
        lastName
    }
}