query healthzCheck{
    healthzCheck{
        error
        info{
            disk{
                status
            }
            memory_rss{
                status
            }
            nestjsApplication{
                status
            }
        }
        status
    }
}