query listChecks($applicantId: String!){
    listChecks(applicantId: $applicantId){
        applicantId
        applicantProvidesData
        createdAt
        downloadHref
        fileName
        fileSize
        fileType
        formUri
        href
        id
        privacyNoticesReadConsentGiven
        redirectUri
        reportIds
        result
        resultsUri
        status
        tags
        webhookIds
    }
}